# Generated by Django 4.2.19 on 2025-02-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.AddField(
            model_name='Student',
            name='nothing',
            field=models.CharField(max_length=25, null=True, blank=True),
        ),
    ]
