# Generated by Django 5.1.6 on 2025-02-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='aadhar_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='address',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='alt_phone_number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='blood_group',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='emailid',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='father_name',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='height',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='mother_name',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='stream',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='student_photo',
            field=models.ImageField(default='student_photo/default.jpg', upload_to='student_photo/'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='weight',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
