# Generated by Django 4.2.16 on 2025-01-24 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mothername', models.CharField(max_length=100)),
                ('fathername', models.CharField(max_length=100)),
                ('guardianname', models.CharField(max_length=100)),
                ('aadharno', models.IntegerField()),
                ('nameinaadhar', models.CharField(max_length=100)),
                ('admissindate', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('pincode', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('alternatenumber', models.IntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('BPL', models.CharField(max_length=100)),
                ('AAY', models.CharField(max_length=100)),
                ('EWS', models.BooleanField()),
                ('CWSN', models.CharField(max_length=100)),
                ('impairment', models.BooleanField()),
                ('CWSN1', models.BooleanField()),
                ('disabilityparc', models.IntegerField()),
                ('nationality', models.BooleanField()),
                ('oosc', models.BooleanField()),
                ('mainstream', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=100)),
                ('admissionno', models.IntegerField()),
                ('dateInput', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('attendence', models.CharField(max_length=100)),
                ('SLD', models.BooleanField()),
                ('ASD', models.BooleanField()),
                ('ADHD', models.BooleanField()),
                ('special', models.BooleanField()),
                ('sports', models.BooleanField()),
                ('scouts', models.BooleanField()),
                ('internet', models.BooleanField()),
                ('height', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('quilification', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
