# Generated by Django 4.2.16 on 2025-01-24 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        )
    ]
