# Generated by Django 4.2.19 on 2025-02-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
