# Generated by Django 4.2.19 on 2025-02-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0004_alter_student_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(default='default.jpg', upload_to='student_photo/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
