# Generated by Django 4.2.19 on 2025-02-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0005_student_student_photo_alter_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(default='student_photo/default.jpg', upload_to='student_photo/'),
        ),
    ]
